[sql_server]
driver = "ODBC Driver 17 for SQL Server"
server = "B2B00024"
database = "AdventureWorks2019"
username = "sa"
password = "welcome"
trusted_connection = false

[postgres]
database = "adventure_db"
username = "postgres"
password = "welcome"
host = "localhost"
schema = "stg"  # Change this to your desired schema name
