

 [mysql]
type = "mysql"
username = "root"
password = "welcome"
host = "localhost"
port = 3306
database = "DummyDb"

 
 
[sql_server]
connection_string = "mssql+pyodbc:///?odbc_connect=DRIVER={ODBC Driver 17 for SQL Server};SERVER=B2B00024;DATABASE=AdventureWorks2019;trusted_connection=yes"

[postgres]
database = "adventure_db"
username = "postgres"
password = "welcome"
host = "localhost"
schema = "test"
