[mysql]
database = "DummyDB"
password = "welcome"
username = "root"
host = "localhost"
port = 3306

[postgres]
database = "sakila_wh"
password = "welcome"
username = "postgres"
schema = "prod"
host = "localhost"
port = 5432
